FROM node:20.20 AS front-builder

ARG VITE_KC_URL=http://localhost:8180
ARG VITE_KC_REALM=ttapi
ARG VITE_KC_CLIENT_ID=ttapi-client
ARG VITE_API_URL=/api/v1

ENV VITE_KC_URL=$VITE_KC_URL
ENV VITE_KC_REALM=$VITE_KC_REALM
ENV VITE_KC_CLIENT_ID=$VITE_KC_CLIENT_ID
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /home/node

COPY frontend .

RUN --mount=type=cache,id=npm-cache,target=/root/.npm \
    npm install \
    && npm run build

FROM nginx:1.27-alpine AS front-runtime

COPY --from=front-builder /home/node/dist /usr/share/nginx/html
COPY --from=front-builder /home/node/nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
